// Register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CHANGE_REGISTER_FORM = 'CHANGE_REGISTER_FORM';

// Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';

// User entities
export const USER_ENTITIES_RECEIVED = 'USER_ENTITIES_RECEIVED';
export const USER_ENTITIES_FAILED = 'USER_ENTITIES_FAILED';
export const SELECTED_ENTITY_CHANGED = 'ACTIVE_ENTITY_CHANGED';

// revenue
export const CREATE_REVENUE_ITEM = 'CREATE_REVENUE_ITEM';
export const REVENUE_ITEM_CREATED = 'REVENUE_ITEM_CREATED';
export const REVENUE_ITEM_FAILED_CREATION = 'REVENUE_ITEM_FAILED_CREATION';
export const DELETE_REVENUE_ITEM = 'DELETE_REVENUE_ITEM';
export const REVENUE_ITEM_DELETED = 'REVENUE_ITEM_DELETED';
export const REVENUE_ITEM_FAILED_DELETE = 'REVENUE_ITEM_FAILED_DELETE';
export const EDIT_REVENUE_ITEM = 'EDIT_REVENUE_ITEM';
export const FINISH_EDITING_REVENUE_ITEM = 'FINISH_EDITING_REVENUE_ITEM';
export const REVENUE_ITEM_CHANGED = 'REVENUE_ITEM_CHANGED';
export const REVENUE_ITEM_CHANGE_FAILED = 'REVENUE_ITEM_CHANGE_FAILED';

// cost
export const CREATE_COST_ITEM = 'CREATE_COST_ITEM';
export const COST_ITEM_CREATED = 'COST_ITEM_CREATED';
export const COST_ITEM_FAILED_CREATION = 'COST_ITEM_FAILED_CREATION';
export const COST_ITEM_DELETED = 'COST_ITEM_DELETED';
export const COST_ITEM_FAILED_DELETE = 'COST_ITEM_FAILED_DELETE';
export const EDIT_COST_ITEM = 'EDIT_COST_ITEM';
export const FINISH_EDITING_COST_ITEM = 'FINISH_EDITING_COST_ITEM';
export const COST_ITEM_CHANGED = 'COST_ITEM_CHANGED';
export const COST_ITEM_CHANGE_FAILED = 'COST_ITEM_CHANGE_FAILED';

// opex
export const CREATE_OPEX_ITEM = 'CREATE_OPEX_ITEM';
export const OPEX_ITEM_CREATED = 'OPEX_ITEM_CREATED';
export const OPEX_ITEM_FAILED_CREATION = 'OPEX_ITEM_FAILED_CREATION';
export const OPEX_ITEM_DELETED = 'OPEX_ITEM_DELETED';
export const OPEX_ITEM_FAILED_DELETE = 'OPEX_ITEM_FAILED_DELETE';
export const EDIT_OPEX_ITEM = 'EDIT_OPEX_ITEM';
export const FINISH_EDITING_OPEX_ITEM = 'FINISH_EDITING_OPEX_ITEM';
export const OPEX_ITEM_CHANGED = 'OPEX_ITEM_CHANGED';
export const OPEX_ITEM_CHANGE_FAILED = 'OPEX_ITEM_CHANGE_FAILED';

// navigation
export const SHOW_SIDE_BAR_MENU = 'SHOW_SIDE_BAR_MENU';

// income statement
export const GET_INCOME_STATEMENT = 'GET_INCOME_STATEMENT';
export const INCOME_STATEMENT_RECEIVED = 'INCOME_STATEMENT_RECEIVED';
export const INCOME_STATEMENT_FAILED = 'INCOME_STATEMENT_FAILED';
export const SHOW_INCOME_STATEMENT_REVENUE = 'SHOW_INCOME_STATEMENT_REVENUE';
export const SHOW_INCOME_STATEMENT_COSTS = 'SHOW_INCOME_STATEMENT_COSTS';
export const SHOW_INCOMESTATEMENT_OPEX = 'SHOW_INCOMESTATEMENT_OPEX';
