// Register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CHANGE_REGISTER_FORM = 'CHANGE_REGISTER_FORM';

// Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';

// User entities
export const USER_ENTITIES_RECEIVED = 'USER_ENTITIES_RECEIVED';
export const USER_ENTITIES_FAILED = 'USER_ENTITIES_FAILED';
